### ISSUE TITLE
Particle Enhancements

### ISSUE THREAD

**Issue by Implausiblyfun** [oakmound/oak#1]
1. Support any shape function.
2. Let size change over time

**Comment by 200sc** [comment]
Particles already support any shape function, afaik.

**Comment by 200sc** [comment]
This is also a breaking change, as it would change the `Size` variable on some generators, which is currently exported.

**Comment by 200sc** [comment]
This is complete on the 2.0 branch as of e985ea4 

However, we might want to reconsider how we do particles in general so that unused features can be disabled (and thus not take additional computation time), like a constructable particle type instead of the four types we have.
