### ISSUE TITLE
When failing to load an image or audio file, optionally provide a still-functional error file

### ISSUE THREAD

**Issue by 200sc** [oakmound/oak#100]
To prevent crashes, we should consider providing an error image or blank audio file when a named file can't be found. There's a lot to consider there with respect to if we can properly size the image.

**Comment by Implausiblyfun** [comment]
For images we need to consider sprite sheets and how that will work as we don't enforce size when loading a sprite sheet.

**Comment by 200sc** [comment]
Thinking about this more, this seems cute but not significant, and difficult to cleanly implement with, as mentioned, sprite sheets. Considering closing as wont do.

**Comment by 200sc** [comment]
Closing as won't do for now.
