### ISSUE TITLE
Resolve OSX deprecation warning

### ISSUE THREAD

**Issue by 200sc** [oakmound/oak#101]
When getting oak, this warning happens:

```
cocoa.m:63:39: warning: 'NSOpenGLCPSwapInterval' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:281:39: note: 'NSOpenGLCPSwapInterval' has been explicitly marked deprecated here
cocoa.m:72:1: warning: method possibly missing a [super prepareOpenGL] call [-Wobjc-missing-super-calls]
```

**Comment by hajimehoshi** [comment]
This will be fixed in GLFW 3.4 https://github.com/glfw/glfw/commit/bac15f94493938eded7161a7a0ab8827584e3db1

**Comment by 200sc** [comment]
Ideally we'd replace the shiny components that involve non-Go code at all to achieve this-- we're just starting investigating this though, having just gotten access to some OSX machines to test on.

**Comment by hajimehoshi** [comment]
https://github.com/golang/exp/blob/master/shiny/driver/mtldriver/mtldriver.go The current Shiny implementation for macOS uses GLFW...
