### ISSUE TITLE
Issue with Shiny dependency

### ISSUE THREAD

**Issue by RingoMckraken** [oakmound/oak#103]
Was attempting to go get the oak/... package and and error keeps occurring when trying to pull shiny v0.4.0

`build github.com/oakmound/oak/examples/bezier: cannot load github.com/oakmound/shiny/unit: module github.com/oakmound/shiny@latest found (v0.4.0), but does not contain package github.com/oakmound/shiny/unit`

Unable run any examples.

Go Version: 1.13.6
- Using go modules
Running POP!_OS 19.04 (System76 fork of Ubuntu)

**Comment by 200sc** [comment]
Yeah, there's been some fluctuation with our dependencies lately and go mod hasn't been very helpful in getting it worked out. I'll look into this.

**Comment by 200sc** [comment]
About to update the readme and make a new release with the new way of getting things with go modules: `go get -u github.com/oak/v2`

**Comment by RingoMckraken** [comment]
Fixed with a clear of cache. Thanks for all the help!
