### ISSUE TITLE
Flickering between multiple polygons 

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#106]
drawing multiple shapes in the same location causes  them to flicker back and forth.

This is not only annoying, but potentially dangerous to those with photosensitive epilepsy.
To prevent this, some sort of z-index or render priority could be implemented, so only the top shape is rendered where they intersect.

 Aside from never having anything with different colors overlap ever, is there any solution to this?

**Comment by 200sc** [comment]
We have z-indexes in the form of layers. Could you share the code you're having trouble with?

**Comment by 200sc** [comment]
@lolbinarycat several examples in the main repo, and several of the larger examples like jeremy and fantastic doctor use this layering strategy extensively. I'd be happy to help with any specific issue you have implementing this on your end.

**Comment by lolbinarycat** [comment]
@200sc yeah, I figured it out, i was looking at the wiki page [The Render Package](https://github.com/oakmound/oak/wiki/The-Render-Package) and didn't see any mention of layers, but the `go doc oak/render.draw` gave me the answer. I probably would have looked more, but I didn't know whether it existed. Closed.
