### ISSUE TITLE
keys autorepeat when held.

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#108]
So I have some code like this:
```
if k, d := oak.IsHeld(currentControls.Jump); k && (d <= time.Millisecond * 30) {
	// Do a jump
}
```
at first it works fine, but if I keep holding the button, the player will start jumping repeatedly. Is there some way to stop this?

**Comment by 200sc** [comment]
Wasn't able to replicate this after a basic test:
```
go func() {
    for {
        if ok, d := oak.IsHeld(currentControls.Jump); ok && d <= time.Millisecond * 30 {
            fmt.Println("duration:",d)
        }
    }
})
```
I tested on windows without changing any keyboard settings. I'll see if changing keyboard auto repeat settings effects this, and then try on linux/mac.

**Comment by lolbinarycat** [comment]
I'm on Linux (using i3wm), so that's my guess for the source.

**Comment by 200sc** [comment]
Yep, replicated on my linux mint setup. I'll see how big of a fix this is, hopefully resolved before tomorrow.

**Comment by 200sc** [comment]
We can disable it by adding 
```
xproto.ChangeKeyboardControlChecked(s.xc, xproto.KbAutoRepeatMode, []uint32{xproto.AutoRepeatModeDefault})
```
To our window creation. However, this appears to turn off Auto repeating keys in every application, not just ours, and it persists after the window is closed (unless we catch the quit and return it to normal. 

Still investigating.

**Comment by 200sc** [comment]
@lolbinarycat I've pushed a fix to the develop branch if you could try it out!

**Comment by lolbinarycat** [comment]
@200sc I believe I'm on develop, and it doesn't seem to have changed anything. One thing I did notice is that pressing another key (like the arrow keys) will stop it, but this seems to simply be a consequence of how autorepeat works. If there was a way to verify I am on branch develop (and have the newest code) that would be much apreciated.

**Comment by 200sc** [comment]
If using modules, you can make sure you're on develop by doing a go get with `@develop`: https://stackoverflow.com/a/55190362. You can double check the mod file has that directive or the commit hash as well where oak v2 is listed. 

If not using modules, you can `git checkout develop` from oak's directory within your gopath, and you'll also need to upgrade `github.com/oakmound/shiny` with `git checkout hotfix/linux-key-repeating`, as that's the source of the fix.

**Comment by lolbinarycat** [comment]
I'm not using modules. I tried `git checkout develop` but I might have messed it up by doing `git branch develop` beforehand. I tried to fix that with `git pull origin develop` but It pulled into master instead. I *think* I got all that sorted but I'm not sure. 

I when I try to do `git checkout hotfix/linux-key-repeating` I get `error: pathspec 'hotfix/linux-key-repeating' did not match any file(s) known to git`.

**Comment by 200sc** [comment]
Are you running that last command from `$GOPATH/src/github.com/oakmound/shiny`? You can also try using the commit hash: `b002461df0023e34a1f1226c4fa7846e4549f65d` (the change is here: https://github.com/oakmound/shiny/commit/b002461df0023e34a1f1226c4fa7846e4549f65d)

This also assumes you aren't vendoring these dependencies

**Comment by lolbinarycat** [comment]
1. Yes
2. How
3. I have no idea what that means

**Comment by 200sc** [comment]
2. `git checkout b002461df0023e34a1f1226c4fa7846e4549f65d`

Vendoring means you would be using a `vendor` directory at the root of your application: https://golang.org/cmd/go/#hdr-Vendor_Directories

**Comment by lolbinarycat** [comment]
Thanks! `git pull` was what I was missing. The fix works. Should this issue be closed now?

**Comment by 200sc** [comment]
Let's close it after it gets released to master

**Comment by lolbinarycat** [comment]
The "fix" turns off autorepeat for everything, even after the program has closed.

**Comment by 200sc** [comment]
Could you write up replication steps? I tested with: 

1. Clicking into and out of the window, ensuring auto repeat was disabled in the window and enabled out of it
2. Closing the window with the red x mark, ensuring auto repeat was enabled after closing
3. Closing the window by `Ctrl+C`ing the terminal, ensuring auto repeat was enabled after closing

I can imagine if the program panics we could fail to catch the panic and it might stay disabled-- we could try to add a panic wrapper that would still do the re-enabling as it exits.

**Comment by lolbinarycat** [comment]
I now think that it was a one-time issue caused by an incomplete setup, not something that was happening everytime.

I switched over to gomodules recently, and now the fix isn't working at all (after setting the autorepeat back to normal).
I suspect that I am no longer using the fixed library in my program.

**Comment by lolbinarycat** [comment]
here's go.mod:
```
module github.com/lolbinarycat/hookshot-oak

go 1.14

require (
	github.com/disintegration/gift v1.2.1 // indirect
	github.com/hajimehoshi/go-mp3 v0.3.0 // indirect
	github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
	github.com/oakmound/oak v1.5.2-0.20191119030332-90a3e010b5d4
	github.com/oakmound/shiny v0.4.2-0.20191207185806-0c20eb569c82 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/stretchr/testify v1.5.1 // indirect
	github.com/yobert/alsa v0.0.0-20200618200352-d079056f5370 // indirect
	golang.org/x/image v0.0.0-20200430140353-33d19683fad8 // indirect
	golang.org/x/mobile v0.0.0-20200329125638-4c31acba0007 // indirect
	golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e // indirect
	golang.org/x/sys v0.0.0-20200327173247-9dae0f8f5775 // indirect
	gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f // indirect
	gopkg.in/yaml.v2 v2.2.8 // indirect
)
```

**Comment by Implausiblyfun** [comment]
There might be a possibility of a race condition with shiny with regards to panics as the window handler is just an event handler in a go routine which could account for auto-repeat staying off.

The oak import itself looks a little suspicious and the shiny import is definitely wrong which is what the change that @200sc added to fix the issue.
Looks like you are no longer on the `fixed` branch of oak.

**Comment by 200sc** [comment]
When using go modules, oak imports have to include the major version like 

```
import (
    oak "github.com/oakmound/oak/v2"
    "github.com/oakmound/oak/v2/dlog"
)
```
Otherwise it'll use oak v1.5 which has some breaking differences from oak 2

**Comment by lolbinarycat** [comment]
I changed to oak v2, now the fix is active.

I figured out how to reproduce the bug, you have to call `os.Exit(0)`

closing the window normally doesn't cause the glitch.

BTW, the code for my program can be found [here](https://github.com/lolbinarycat/hookshot-oak)

**Comment by 200sc** [comment]
Without a wrapper program, we can't capture os.Exit. There are a few approaches I can think of:

1. Easiest, don't support os.Exit and ensure oak has an exit function that acts almost the same with this additional cleanup
2. Move auto repeat handling to oak entirely, using predictive pattern matching to recognize when key presses are from an auto repeat. We could even send a 'IsRepeat' flag with key events to let different events handle repeats specially.
3. In addition to 2, add a startup flag that enableds our existing fix, as it's significantly more performant than time checking key inputs.

**Comment by 200sc** [comment]
I've made an attempt alike to 2. above, without the `IsRepeat` flag work-- this required some deep, painful changes to how we process events for x11 in shiny, but it shouldn't have the same problem as the last solution at least. 

I added a comment detailing the problem in depth there: https://github.com/oakmound/shiny/blob/6df262b8905562d8e77a6d6c73415970fecca06f/driver/x11driver/screen.go#L153

**Comment by lolbinarycat** [comment]
I updated oak, and the fix seems to be working, and without affecting performance enough for me to tell the difference without testing (i.e. by just looking at it).
