### ISSUE TITLE
Improving the wiki

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#109]
right now the wiki doesn't have much information on it. I would be willing to write up some stuff for it, but It doesn't seem like I'm able to.

**Comment by 200sc** [comment]
It looks like there are a few tricks people can use to enable pull requests against a github wiki, which would be the easiest route-- I'll look more into how we could do this.

**Comment by 200sc** [comment]
The easiest setup looks like it's us copying a repo representing the wiki to a new repo, accepting PRs to that repository and adding a pipeline to sync that with the wiki here (or doing the sync manually).  It could also be a subdirectory in oak itself.

**Comment by lolbinarycat** [comment]
That seems like it would work.

**Comment by 200sc** [comment]
I've written up https://github.com/oakmound/oak-wiki with a github actions pipeline to auto-copy changes from there to the wiki here.

**Comment by lolbinarycat** [comment]
Does it support creating new pages?

**Comment by 200sc** [comment]
Yes, just add a new markdown file in the PR
