### ISSUE TITLE
window/camera controls are confusing and don't seem to work.

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#111]
I've been working on [this](https://github.com/lolbinarycat/hookshot-oak/tree/camera) project, and have been having lots of trouble with the functions that relate to window/screen size. There are a few factors contributing to this.
1. There are a lot of similar commands, and the difference between them is not well explained.
there's `ChangeWindow` , `MoveWindow`, `SetAspectRatio` , `SetViewportBounds`, `SetScreen`, and probably more.
2. I'm using a tiling window manager (specifically i3), so many concepts don't translate well, like screen position.
i3 does have floating windows, but you have to use a keyboard shortcut for most windows, although some (like loading windows for programs) open like this automaticaly.
3. `SetFullscreen` and `SetBorderless` don't work. Perhaps related to the previous point?
4. The game I'm working on requires strict control over the visible area (It has a screen-based camera, like zelda 1)
5. Many functions often don't work correctly and sometimes crash the program. 
For example, calling `ChangeWindow` before `oak.Init` results in segfault.
More problematicaly, `SetViewportBounds` doesn't seem to properly set viewport bounds, so there is a space between screens that you can't see, (you can tell by holding rightshift, this will center the camera on the player)

**Comment by 200sc** [comment]
I agree that these options are many and its not well documented how they interact. This is at least in part because they've all been added over time and old ones weren't able to be changed for backwards compatibility. 

In terms of SetScreen and SetViewportBounds-- does the top down shooter example present correctly for you? (https://github.com/oakmound/oak/wiki/A-Top-Down-Shooter) -- the gif at the very bottom shows how the camera moving with the player should display 

There is also a fullscreen/borderless example program (https://github.com/oakmound/oak/blob/master/examples/screenopts/core.go)-- does that run correctly for you? I don't know if we've tried this with a tiling window manager.

There's a few functions like ChangeWindow that are ineffective or panicky if run before `oak.Init`-- like loading a font in the render package IIRC. We can certainly get rid of specific panics but they'll likely stay ineffective because the system isn't in place to do the operation requested. 

I can also try to write up a example that does strict camera transitions like rooms in a zelda dungeon.

**Comment by 200sc** [comment]
I've added an example demonstrating the use of screen commands for a zelda-like game. It's called 'rooms' on develop. I also tested the screenopts program on my linux setup and fullscreen and borderless were both working. I can try to get a setup using the specific window manager you're using to test them over there as well. Attached is a gif of what the new demo does: 
![rooms-example](https://user-images.githubusercontent.com/4564184/85236897-b6911480-b3e7-11ea-9272-aee5873e87e5.gif)

**Comment by lolbinarycat** [comment]
I tried top down shooter and screenopts demos, the first one worked fine, and the second one was mostly fine too, but if I enabled borderless mode, I couldn't disable it.

**Comment by lolbinarycat** [comment]
tried out the rooms demo, it seems to work fairly well (although the screen gets stretched unless I make it a floating window). I'll have to take a look at the code.

**Comment by lolbinarycat** [comment]
I tried using your method for camera control in my game, and although the fancy transition is broken (likely because it is run in a separate thread at a different rate, and can't lock the player's movement), which is fine because I didn't have that in my version originally, It seems to work fairly well.

The problem I have now, is that the units in-game seem to be different to the ones used for the game, or else the viewport bounds aren't getting set properly. 
I have a 800 unit wide rectangle positioned at -800 units. I want each screen to be 800x600 (and thus that should be the size of the viewport bounds), but after going 2 screens to the left, you can still see this rectangle.
I also still have the problem of the screen being stretched dramatically (square looks close to a 2x1 rectangle).

**Comment by 200sc** [comment]
So ViewportBounds aren't implemented as you are describing them-- ViewportBounds are hard limits on where the viewport can move to, they aren't partial limits or grid-based. I would look at how they are used in the top down shooter demo as an example, but based on your description, I wouldn't use ViewportBounds:

If I had a design like this that should work like the rooms demo, where each square is 800 x 600:

[A] - [B] - [C] - [D]
 |       |       |       |
[E] - [F] - [G] - [H]

And I wanted to make sure the window never showed anything outside of those 8 squares, I would set the viewport bounds to
X;0, Y:0, W: 800x4, H:600x2

This would mean that if other code in the engine tried to use SetScreen or ShiftScreen to go outside of those eight rooms, the change would be rejected. 
But ideally I would also put blocking terrain along the outer walls, so unless the view followed the player, the viewport bounds wouldn't matter.

As far as the screen stretching goes, I have never used a tiled window manager but theoretically the aspect ratio controls should help with the actual play area not stretching-- this is usually done pre-`oak.Init` via `oak.SetAspectRatio`. I can try to get a distro running with your window manager to test this out or write another example.

**Comment by lolbinarycat** [comment]
I tried `SetAspectRatio`, but it ended up making the visuals squished instead. 
The main problem, is that I can't decide how much of the world I want to show (basicaly a zoom level, preferably with x and y independent).

**Comment by 200sc** [comment]
@lolbinarycat 
We've just added a zoom example to develop that shows how you could control this with the renderable interface (the example could be extended to incorporate more than one renderable inside, for example). 

It uses a naive zooming method for zooming in, but that be easily be replaced with a googled zoom in algorithm

**Comment by lolbinarycat** [comment]
I took a look at the example, and I barely understand how it works.

It looks like it is operating on the pixel buffer? This seem far too advanced for something like changing the zoom level of the screen. I was hoping for something like `SetCameraSize(W int,H int)`)
Also, it seems to operate on one object, which doesn't work for what I want to do.

After digging through the code, I found what I was looking for:
`oak.SetupConfig.Screen = oak.Screen{Height:600,Width:800}`

Also, if we're going to be exporitng `oak.ScreenWidth` and `oak.ScreenHeight` directly, and not through a getter function, maybe we should include a disclamer in the docs that they are overwritten during `oak.Init`, otherwise It makes it seem like we could change these to change the screen Width/height, which is not the case.

P.S. Sorry for the late reply, I got caught up trying to do something else.

**Comment by 200sc** [comment]
Ah! We thought you were trying to do some kind of dynamic zoom in / zoom out like on GTA 2. Yes, the SetupConfig is where those initial settings should go. 

We'll look into making documentation about this clearer.

**Comment by lolbinarycat** [comment]
That was the biggest problem, but I still can't get `SetAspectRatio` to work correctly. Now I think I was putting the numbers in wrong (xToY isn't exactly clear), but the problem is when I put it in the other way, I just get a black screen.

**Comment by 200sc** [comment]
You could use a handler that lets you set it manually while the program is running via the command line to see what value you want to use;:

```
		oak.AddCommand("setAspectRatio", func(args []string) {
			if len(args) != 1 {
				fmt.Println("Usage: setAspectRatio .75")
			}
			xToY, err := strconv.ParseFloat(args[0], 64)
			if err != nil {
				fmt.Println("failed to parse floating point ratio")
			}
			oak.SetAspectRatio(xToY)
			oak.ChangeWindow(oak.ScreenWidth, oak.ScreenHeight)
		})
```

**Comment by lolbinarycat** [comment]
This reply is a bit late, but I think I figured out the root of the problem. I was previously using `oak.SetAspectRatio(8/6)`, and the screen would end up at around 1:1, however when I set it to `1.3333` (which approximates 8/6), it worked as expected.
So, it would seem that oak.SetAspectRatio() does not like repeating decimals (this is confirmed by 16/9, as well as 800/600)

**Comment by 200sc** [comment]
That is a Go language feature. Integer division vs float division.

See this playground: https://play.golang.org/p/LlVLnoPL4Mt

**Comment by lolbinarycat** [comment]
I guess I kinda thought go wouldn't do integer division with number literals, but I guess that would be more confusing than helpful. I think this issue could be closed now.

**Comment by 200sc** [comment]
OK, we will do a documentation pass soon on notes that came up here.
