### ISSUE TITLE
Warn about the limited range of event.BindingOption.Priority

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#122]
Using a value over 32 causes an index out of range error, this should be mentioned in the docs for it.

**Comment by 200sc** [comment]
There are docs, but they are not exposed in the godoc, correct https://github.com/oakmound/oak/blob/master/event/bus.go#L30-L39

We should certainly move something similar out.

**Comment by 200sc** [comment]
This is addressed by https://github.com/oakmound/oak/commit/2c7c49707426dcdba2fca3629fba51efd999cf30
