### ISSUE TITLE
Change event.CID to an alias of int.

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#137]
Instead of `type CID int` have `type CID = int`.
The reason for this is of course the fact that they are use pretty much interchangeably throughout the code.

**Comment by Implausiblyfun** [comment]
I do admit that the whole int versus CID thing is pretty annoying. 
However due to the existence of https://github.com/oakmound/oak/blob/master/event/cid.go#L18 its probably something to revisit with the push to 3.0

**Comment by lolbinarycat** [comment]
I'm not 100% sure what you're saying, but if oak was changed to only ever use `CID` and never `int`, there would be no need for this change.

**Comment by 200sc** [comment]
Taking this issue in isolation-- to clarify, there are methods on CID, so it can't be an alias, as you can't add methods to built in types. 

Using CID more often is a preferable approach.

**Comment by lolbinarycat** [comment]
Yeah, that makes sense.
