### ISSUE TITLE
can debug console be disabled? (using lots of CPU)

### ISSUE THREAD

**Issue by glycerine** [oakmound/oak#147]
I was still seeing alot of high CPU use under idle conditions, so I profiled again and I see that even when idle, the debug console is chewing through alot of cpu. Is there any means (or harm) to shut it off?

![image](https://user-images.githubusercontent.com/445247/108460686-ca26a080-723e-11eb-986c-fe0f7dfefb48.png)

**Comment by 200sc** [comment]
We can certainly add a flag, but I would be really surprised if something waiting on stdin was eating CPU.

**Comment by 200sc** [comment]
The upcoming release should add the configuration to disable the console input.

**Comment by 200sc** [comment]
Flag added, merged and tagged. Feel free to reopen if there's a bug with the implementation.

**Comment by glycerine** [comment]
Thanks Patrick!
