### ISSUE TITLE
Warnings about undefined: EncodeBytes during go get

### ISSUE THREAD

**Issue by peterhellberg** [oakmound/oak#15]
I just installed oak by following the instruction in the README:

```
go get -u github.com/oakmound/oak/...
```

## Got this output

```
# github.com/200sc/klangsynthese/audio
../../200sc/klangsynthese/audio/encoding.go:18: undefined: EncodeBytes
../../200sc/klangsynthese/audio/encoding.go:23: undefined: EncodeBytes
../../200sc/klangsynthese/audio/format.go:28: undefined: EncodeBytes
```

## Expected

No output

## Software

```
$ go version
go version go1.8.3 darwin/amd64
```

```
    System Software Overview:

      System Version: macOS 10.12.5 (16F2073)
      Kernel Version: Darwin 16.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Peter’s MacBook
      User Name: Peter Hellberg (peter)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 12 days 21:52
```

**Comment by 200sc** [comment]
This is referenced by [this PR](https://github.com/200sc/klangsynthese/pull/21) in the audio library

**Comment by 200sc** [comment]
See [the klangsynthese  issue](https://github.com/200sc/klangsynthese/issues/14)

**Comment by peterhellberg** [comment]
The changes in https://github.com/200sc/klangsynthese/pull/21 now allows me to install oak without any warnings.

```
~/Go/src/github.com/oakmound
$ go get -u github.com/oakmound/oak/...
~/Go/src/github.com/oakmound
$
```

And I can now start the pong example.

<img width="432" alt="oak-pong-example" src="https://user-images.githubusercontent.com/565124/28379164-0c56bfca-6cb3-11e7-91f6-d7a0e6589c00.png">
