### ISSUE TITLE
Q: guidance on avoiding slow/slowing fps?

### ISSUE THREAD

**Issue by glycerine** [oakmound/oak#151]
Arg. My screen flickers badly between redraws, and I'm only updating every 1 second.  As in, there is a flash of black that is jarring to the eye.

I'm probably not doing something right. Can you offer any guidance... should I be using sprites or something?  

I'm just getting familiar with oak so I've probably missed something important.  

I extracted out a minimal reproducer here:
https://github.com/glycerine/oak-heatmap

Thanks for any suggestions.

**Comment by glycerine** [comment]
Ah. I was doing the frame reset, then some computation, then the draw. If I reset just before the draw, my flicker goes away. yay.

But I can still see the frames-per-second dropping rather drastically as it goes. And it doesn't start out very fast to begin with.  So I still feel like I must be doing something wrong! :)

~~~
frames per second: 3.330230282849791
frames per second: 1.8942291696258762
frames per second: 1.3786437360992423
frames per second: 1.1691374838084938
frames per second: 1.0280696488776753
frames per second: 0.8600747055522376
frames per second: 0.5505714120788732
frames per second: 0.4021465435357518
frames per second: 0.31203473710460045
frames per second: 0.25351023969762115
~~~

**Comment by glycerine** [comment]
So I've been studying this, and apparently it is unrelated to oak.  I can see it happening even if I don't initialize oak at all(!)

Maybe I'm making too much garbage for the Go GC.

Still looking...

**Comment by 200sc** [comment]
It's the `n = 0` line. If you switch to a `n % 30 == 0` and remove it, you get: 

```
frames per second: 8.839123184908152
frames per second: 9.396284640147199
frames per second: 9.41323390866496
frames per second: 9.64513994941333
frames per second: 9.925558838077556
frames per second: 10.063455960178235
frames per second: 10.266187076033972
frames per second: 10.249401899355101
frames per second: 10.265963666655765
frames per second: 10.36054707266386
frames per second: 10.448328399801525
frames per second: 10.5455873261163
frames per second: 10.640038996015742
frames per second: 10.695187193010407
frames per second: 10.620722309376657
frames per second: 10.674613608120186
frames per second: 10.685215418447388
frames per second: 10.750119210361301
frames per second: 10.724264299523766
frames per second: 10.642731268106955
frames per second: 10.673172219257452
frames per second: 10.703685416739477
```

**Comment by glycerine** [comment]
Maybe it is just my old 2015 mac, but if I watch it for 60 seconds, I can definitely see some pauses and measure a slow down too.

~~~
frames per second: 3.605239592907098
frames per second: 7.668326442610551
frames per second: 7.411444278366908
frames per second: 7.757146601761318
frames per second: 6.7186196652871555
frames per second: 6.295715696844995
frames per second: 5.50629872274465
frames per second: 3.9171000207409272
frames per second: 3.2537850301052473
frames per second: 5.911345770528841
frames per second: 5.850716369435219
frames per second: 6.0343382473173
frames per second: 5.908622775354188
frames per second: 5.43390869639194
frames per second: 6.1714856384156915
frames per second: 1.2929852223328981
frames per second: 5.808705104920497
frames per second: 5.0713846034417385
frames per second: 5.5849178141701294
frames per second: 5.549491698941661
frames per second: 1.3002300575878172
frames per second: 1.271161610744274
frames per second: 1.2095065011137114
frames per second: 0.5400947339881822
frames per second: 2.9660449578685664
frames per second: 3.6298962238623353
frames per second: 3.2036648247729342
frames per second: 2.7001894252546705
~~~

Back to my original question-- just out of curiousity, is there any more efficient way to render such a grid?

**Comment by 200sc** [comment]
Yeah, there's a diff that i kept around without thinking about it to reduce GC pressure:

probably still not the most efficient way of doing this, but an improvement from what I can measure:

```go
        var lastHeat *Heatmap

	oak.Add("heatmap",
		// Init
		func(string, interface{}) {
			oak.SetViewportBounds(0, 0, fieldWidth, fieldHeight)
		},

		// Loop
		func() bool {
			select {
			case df := <-drawMeCh:
				heat := NewHeatmap(0, 0, df)
				render.Draw(heat.Mov.R, 1)
				if lastHeat != nil {
					lastHeat.Mov.Destroy()
				}
				lastHeat = heat
			}
			return true
		},
		func() (string, *scene.Result) {
			return "heatmap", nil
		})

	oak.Init("heatmap")
```

Replacing the draw stack is intended to be a uncommon, scene setup sort of action-- the destroy on the entity itself here cleans up each entity when the new one comes in to replace it.

With that I get around 10-12 in the measurements. 

Trying out some other things.

**Comment by 200sc** [comment]
Removing the bounding box in `colorCell` adds an additional 2-3 frames for me-- the color box is the same dimensions as the bounding box so adding the bounding box just makes the draw take longer. Using the other bounding box implementation would also be more performant.

**Comment by glycerine** [comment]
Cool.  Yeah, I see the speedup if I take out the bounding box too.

**Comment by glycerine** [comment]
lastHeat.Mov.Destroy() is huge boost in fps! thank you for that suggestion.  I knew I wasn't doing it right.
