### ISSUE TITLE
Q: respond to close window click on linux? 

### ISSUE THREAD

**Issue by glycerine** [oakmound/oak#153]
Just wondering how my app can respond to the user clicking the close window X button (kubuntu 18.04) in the outermost window corner. On OSX the window shuts down automatically, but not in x11. I couldn't locate a message or callback to handle this. Can someone point it out?

**Comment by 200sc** [comment]
The event to respond to should be `event.OnStop` (https://github.com/oakmound/oak/blob/master/event/strings.go#L33). 

Let me know if this isn't getting triggered, I can look into it in the internals to see if there's a bug there.

**Comment by glycerine** [comment]
Thanks Patrick! I'll try that.

**Comment by 200sc** [comment]
I somehow missed the last comment on this issue, and will be looking into this shortly.

**Comment by 200sc** [comment]
On my usual box (cinnamon) the x button does close the window, I'll get a kubuntu image and test that out.

**Comment by 200sc** [comment]
Failed to replicate on kubuntu as well. What I did:
1. Downloaded kubuntu image
2. Installed on virtual box instance
3. Downloaded Go 1.16.5 
4. Checked out Oak v3 via `go get github.com/oakmound/oak/v3@latest`
5. Ran pong example
6. X closed window successfully

Again, sorry for taking so long for getting to this. Screenshot of the kubuntu version I used:

![Screenshot from 2021-06-13 08-43-49](https://user-images.githubusercontent.com/4564184/121809880-3715da00-cc24-11eb-8aaa-fbeafe1e0c3a.png)

**Comment by glycerine** [comment]
so might be a kubuntu version thing. thanks for letting me know.

**Comment by 200sc** [comment]
Scratch that, I actually replicated this on mint, looking into supporting multi-window on linux. We never called `Release` on windows when they were manually closed. 

I never saw it in my previous testing because the program would always exit after `oak.Init` exited.
