### ISSUE TITLE
Bezier curves Package

### ISSUE THREAD

**Issue by Implausiblyfun** [oakmound/oak#2]
Modify has a simple implementation but this should be pulled out to a separate more fully featured package

**Comment by 200sc** [comment]
This probably doesn't need to be a package but just a new type / function set in render?

**Comment by 200sc** [comment]
Looking into this more, we could consider using https://github.com/llgcode/draw2d. The only reason I'm not so sure about that is that is that we really just want a way to draw arbitrarily complex bezier curves, and while this library provides a couple of bezier functions it doesn't expand past cubic.

**Comment by 200sc** [comment]
This should be reviewed before it gets pushed to master, but I wrote up a small interface for Bezier curves that's now in the render package in develop. It might not belong in that package, as it just does float math. It's more and more looking like we should have a floatgeom library to match our intgeom library.

**Comment by 200sc** [comment]
This has been tested to my satisfaction in the bezier example.
