### ISSUE TITLE
这个应该会死锁吧？

### ISSUE THREAD

**Issue by czxichen** [oakmound/oak#33]
func lifecycleLoop(s screen.Screen) {
	initControl.Lock()
	if lifecycleInit {
		dlog.Error("Started lifecycle twice, aborting second call")
		return
	}
	lifecycleInit = true
	initControl.Unlock()
	dlog.Info("Init Lifecycle")

**Comment by 200sc** [comment]
See #3

**Comment by 200sc** [comment]
If that issue doesn't answer your question, feel free to reopen this, but I don't think anyone on this project knows your language.

**Comment by czxichen** [comment]
sorry,What I mean is that this code will be a deadlock

func lifecycleLoop(s screen.Screen) {
initControl.Lock()
if lifecycleInit {
dlog.Error("Started lifecycle twice, aborting second call")
initControl.Unlock  //add this line
return
}
lifecycleInit = true
initControl.Unlock()
dlog.Info("Init Lifecycle")

**Comment by 200sc** [comment]
Yeah, we've put a commit in to develop that adds that earlier today, but if multiple goroutines enter this function at all there's a problem-- whether they lock or return doesn't change the intended functionality of only letting one goroutine get through ever
