### ISSUE TITLE
Support Scalable Vector Graphics 

### ISSUE THREAD

**Issue by Implausiblyfun** [oakmound/oak#4]
Oak should be able to import SVG

**Comment by 200sc** [comment]
We should probably decide on an existing SVG package to support for this, so we don't need to do a huge amount of work ourselves?

**Comment by 200sc** [comment]
I don't think we should try to tackle this before other things that we have a much better use case for (JS, the shiny fork). It'll probably take a lot of time to do this, but when we do we should refer to this https://www.w3.org/TR/SVG11/

**Comment by lu4p** [comment]
Is this what you are looking for https://godoc.org/github.com/goki/gi/svg ?

**Comment by Noofbiz** [comment]
That is based on [oksvg](https://github.com/srwiley/oksvg). It's less embedded in the framework and easier to work with than goki's when I was looking for a parser.

**Comment by 200sc** [comment]
`oksvg` looks solid. We should try to make an example that utilizes it, and if its stable enough we could add it directly to `render`.

**Comment by 200sc** [comment]
New example demonstrating theoretical support, without extending the supporting libraries:
https://github.com/oakmound/oak/commit/5189ff1a0f6d92b4a49fc4dfe975193d524c34f4

With the libraries not supporting text and not supporting rendering to non-standard library draw.Image interfaces (apparently at least, in testing), I don't think its appropriate to integrate it into the engine by default right now. With small changes you could convert this example into a renderable itself that re-wrote its sprite component whenever the bounds of the svg were updated.
