### ISSUE TITLE
ARM architecture?

### ISSUE THREAD

**Issue by shingtaklam1324** [oakmound/oak#48]
Does Oak cross-compile / compile on a Linux Machine with ARM architecture (eg. a Raspberry Pi)?

**Comment by 200sc** [comment]
I believe so, but I'll run some tests and get back with a better answer. There are probably practical concerns right now in terms of the engine being on the heavy side when dealing with limited resources, but we're working on providing settings to disable functionality for reduced overhead.

**Comment by 200sc** [comment]
Update: aside from audio, yes. 

It looks like the alsa library we use for linux audio just supports linux + amd64.
