### ISSUE TITLE
Add Directionality Helpers

### ISSUE THREAD

**Issue by 200sc** [oakmound/oak#55]
We ran into an issue today where we needed to represent explicit directions, and we didn't want to represent them as vectors. We've resolved this problem a number of times but couldn't use an existing solution due to circular dependencies. This might justify the addition of directional types (perhaps to alg). This would be something along the lines of 

`type Direction2 int`
`type Direction3 int`

With associated consts

```
const(
    Up Direction2 = iota
    Right Direction2
    Down Direction2
    Left Direction2
    
    North Direction2
    East Direction2
    South Direction2
    West Direction2
)
```

etc. 

However, there would need to be a good way to abstract the similarity between these directions, at least in part via conversion to `floatgeom.PointX`es, and we would need a good way to abstract the different groups of directions-- relative vs cardinal, angle between points in a set. It would make sense for there to be a set of points for 4-way, 4-way-diagonal, 8-way, and 6-way movement, for different tile layout types-- expanding this to 3 dimensions in similar sets as well. This would require that a `Direction` has a query function for knowing what `DirectionType` it is in, and at this point it looks like direction should be it's own package.

**Comment by Implausiblyfun** [comment]
With the release of 2.1 we have most of this. We need to loop back to this to get the requested cardinal names. 

Additionally per conversation with @200sc  we need to consider moving where the directions are stored to potentially no longer be part of the mod package.

**Comment by 200sc** [comment]
Resolving this with 2.3.0
