### ISSUE TITLE
A vertical line is drawn with thickness = 1 regardless of thickness value passed in

### ISSUE THREAD

**Issue by deniscormier** [oakmound/oak#57]
When drawing a vertical line (xDelta == 0), the function goes into a corner case that sets thickness equal to 1 regardless of value passed in.

The offending line is here:
https://github.com/oakmound/oak/blob/04566b7920fe2bde2456172902e9d36a9487064b/render/line.go#L128

The desired behaviour is to allow vertical lines to be drawn at different thicknesses (while applying color + color gradients properly).

**Comment by 200sc** [comment]
Thanks for pointing this out. It should be a quick fix, I'll get on it sometime later today unless you want to PR a fix before that.

**Comment by 200sc** [comment]
The same bug happens for the `yDelta == 0 && xDelta == 0` block as well. This is an artifact of when this code just handled 0-thickness lines.

**Comment by 200sc** [comment]
Could you try the most recent commit from develop?

**Comment by deniscormier** [comment]
Just tried my little project on it (some dice game I'm trying to put together) and the vertical line is rendered as expected. Also left some feedback on the commit that you can apply (or not) at your leisure. Feel free to close the issue when the fix is in the appropriate branch.

Thanks for applying the fix and addressing the issue so quickly! I can't wait to see if I can actually crank out a game with this thing. In general, it's been hard to figure out how to use the framework with examples/docs (technically all there, but still tough to process), but the way the framework is set up makes very little code do a lot 👍

**Comment by 200sc** [comment]
Thanks for the feedback. There's a need to write tutorials that answer "how do I do X" for a bunch of different things, yes. We're waiting on 2.0 for that so we don't need to go through and update all of the code in those tutorials. 

A lot of the references for functions are insufficient as well. If you note something that could be documented better, let us know (maybe on #35) and we'll get on it.

**Comment by 200sc** [comment]
1.4.1 merges this into master.
