### ISSUE TITLE
How to launch ? 

### ISSUE THREAD

**Issue by ShizuCarry** [oakmound/oak#64]
Hey, i'm newbie at making games, so i don't know how to launch or compile the exemple files.
Some help ? :)

**Comment by 200sc** [comment]
Once you've gotten the project via `go get`,  run `go run $x.go` where `$x` is the file you'd like to run.

**Comment by 200sc** [comment]
Oak is a game engine in the Go programming language. You'll need to install Go to compile it. See https://golang.org

**Comment by ShizuCarry** [comment]
Damn, i didn't saw the download button.
Thanks :)
And finished game would be exportable in .exe ?

**Comment by 200sc** [comment]
Go compiles natively on all desktop platforms, so for windows you will get an exe file, yes.

**Comment by ShizuCarry** [comment]
http://prntscr.com/hizctj
It say "don't find file name like it "

**Comment by 200sc** [comment]
`flappyBird` is a directory, and there is a go file to run inside of the directory.

**Comment by 200sc** [comment]
I'll close this issue within the next week if this stays inactive, as the issue is a filesystem / golang concern and not really realted to oak.
