### ISSUE TITLE
Add polygon clipping support, remove polyclip-go dependency

### ISSUE THREAD

**Issue by 200sc** [oakmound/oak#72]
Polyclip-go has notable bugs that limit our ability to represent renderable dimensions. We should reinvent the wheel and fix those bugs.

**Comment by 200sc** [comment]
We really only need `does 2D rectangle intersect 2D polygon`. The algorithm should be:
1. If the bounding box of the polygon doesn't intersect the rectangle (see collision package 
for example checks), then `false`
2. Else for each line segment  `AB` in the polygon, if either `A` or `B` lies inside the rectangle or if `AB` intersects either diagonal of the rectangle, return true.
3. Return `false` otherwise.

**Comment by Noofbiz** [comment]
Separating axis theory works great for ellipses, polygons, and AABBs and can even be faster than that since it doesn't need to check every side each time. A good explanation can be found [here](http://www.metanetsoftware.com/technique/tutorialA.html)

**Comment by 200sc** [comment]
Yeah if the draw polygon is a rectangle as well, then we could break out early.

**Comment by 200sc** [comment]
This is as complete as it can be prior to 3.0, where we can remove the (effectively unused) import. A new method has been added and the old method now calls the new method after transforming the polyclip input.
