### ISSUE TITLE
It's a little misleading to say it is "Pure Go"

### ISSUE THREAD

**Issue by 131072** [oakmound/oak#79]
This library specifically uses a library called "github.com/tryphon/alsa-go" which uses C. It causes confusion for people who think that it will inherently work with GopherJS if it is "pure go", but it obviously doesn't due to it's C dependency.

**Comment by 200sc** [comment]
On linux, yes. That's why it's noted as an exception in the readme: 

> (We are very sad about the linux audio dependency and are considering writing an audio driver just to get rid of it.)

Oak is pure Go on Windows, pure Go minus audio on Linux.

**Comment by SkyrisBactera** [comment]
Just curious, what is stopping us from using one of the pre-existing audio libraries such as Oto?

**Comment by SkyrisBactera** [comment]
I understand that this wouldn't resolve the "Pure Go" issue, but what is stopping us from using oto instead of the alsa bindings so that we can use Oak in the browser with GopherJS?

**Comment by 200sc** [comment]
Nothing. Oak is split into component libraries like audio and collision so that users can replace individual components at their leisure. Other than loading audio files at the start of the engine, Oak doesn't do anything (and none of the helpers in entities do anything) to interact with its audio sub-library and so you're welcome to use oto instead.

**Comment by 200sc** [comment]
There are other obstacles before using oak with GopherJS: A) performance is terrible without using webGL, and B) GopherJS isn't as easy as it sounds to just plop libraries in and have everything work. The latter issue is resolved in the `js-2.0.0` branch, but that branch is in need of an update.

**Comment by 131072** [comment]
Ah ok. Thanks for the help!
