### ISSUE TITLE
Support Fullscreen

### ISSUE THREAD

**Issue by Implausiblyfun** [oakmound/oak#8]
Window manager Shiny does not currently let Oak support fullscreen. This should be fixed if possible.

**Comment by 200sc** [comment]
Depends on #40

**Comment by 200sc** [comment]
Work on this started a while ago in relase/2.0.0, but the real work to get it done needs to happen in oakmound/shiny

**Comment by 200sc** [comment]
For windows, should refer to this: https://stackoverflow.com/questions/2382464/win32-full-screen-and-hiding-taskbar

**Comment by 200sc** [comment]
Support on windows is complete.

**Comment by 200sc** [comment]
Support on linux through the x11 driver is complete. We don't have the equipment to test the gldriver for mac or linux, but that will continue to be tracked through oakmound/shiny#4
