### ISSUE TITLE
Window Should be Programatically Resizable

### ISSUE THREAD

**Issue by Implausiblyfun** [oakmound/oak#9]
Currently resizing of the window is fully on the implementing user.
Oak should be able to programmatically resize a window regardless of content.

**Comment by 200sc** [comment]
Depends on #40

**Comment by 200sc** [comment]
This is supported on windows now. A little bit more looking into why the x11 driver isn't accepting our positional arguments needs to happen for linux, and a computer to test on needs to happen for OSX (so OSX isn't a requirement for 2.0)

**Comment by 200sc** [comment]
As the linux x11driver supports window positioning, this is done for 2.0 The issue will continue to be tracked for other shiny drivers at https://github.com/oakmound/shiny/issues/3
